a=int(input("Enter first number"))
b=int(input("Enter second number"))
add=(a+b)
mul=(a*b)
div=(a/b)
sub=(a-b)
mod=(a%b)
exp=(a**b)
floor=(a//b)
print(f"The sum={add} product={mul} division={div} subtaction={sub} modulus={mod} exponetiation={exp}   floor_division={floor}")
